version: '3.8'

services:
  webserver:
    container_name: webserver-globalmart
    build: ./
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
  
  db:
    container_name: db-master-globalmart
    image: postgres:14.7-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=globalmart

  db-replica1:
    container_name: db-replica1-globalmart
    image: postgres:14.7-alpine
    volumes:
      - pgdata_replica1:/var/lib/postgresql/data/
    ports:
      - 5433:5433
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=globalmart
      - PGPORT=5433

  db-replica2:
    container_name: db-replica2-globalmart
    image: postgres:14.7-alpine
    volumes:
      - pgdata_replica2:/var/lib/postgresql/data/
    ports:
      - 5434:5434
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=globalmart
      - PGPORT=5434

  pgadmin:
    container_name: pgadmin4-globalmart
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@globalmart.in
      PGADMIN_DEFAULT_PASSWORD: root123
    ports:
      - "5051:80"

volumes:
  pgdata:
  pgdata_replica1:
  pgdata_replica2:
  